# Generated by Django 2.2.2 on 2019-07-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='輸入疾病名稱', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='輸入病人姓名', max_length=200)),
                ('personalid', models.CharField(help_text='輸入病人身分證字號', max_length=200)),
                ('bloodtype', models.CharField(help_text='輸入病人血型', max_length=200)),
                ('date_of_birth', models.DateField(help_text='輸入病人出生年月日')),
                ('illness', models.ManyToManyField(help_text='請選病人患有什麼疾病', to='catalog.Illness')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_detail', models.TextField(blank=True, help_text='診斷紀錄', max_length=400)),
                ('date', models.DateField(help_text='診斷日期')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Patient')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
