# Generated by Django 2.2.2 on 2019-07-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='treatment',
        ),
        migrations.AddField(
            model_name='treatment_record',
            name='medication',
            field=models.ManyToManyField(blank=True, help_text='藥物使用', to='catalog.Medication'),
        ),
    ]
