# Generated by Django 2.2.2 on 2019-07-16 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='return_date',
            field=models.DateField(blank=True, default=datetime.date.today, help_text='下次約診日期'),
        ),
    ]
