# Generated by Django 2.2.2 on 2019-07-18 07:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_patient_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='illness',
            name='selection',
            field=models.CharField(choices=[('severe', '重大疾病'), ('minor', '一般疾病')], default='minor', help_text='請選疾病是否為重症', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.PositiveIntegerField(default=180, help_text='輸入病人身高(cm)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_illness',
            field=models.ManyToManyField(help_text='請選病人過去病史', related_name='past_illness', to='catalog.Illness'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.PositiveIntegerField(default=70, help_text='輸入病人體重(kg)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='illness',
            field=models.ManyToManyField(help_text='請選病人患有什麼疾病', related_name='illness', to='catalog.Illness'),
        ),
        migrations.CreateModel(
            name='Severe_illness_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='發病日期')),
                ('illness', models.OneToOneField(help_text='重症名稱', on_delete=django.db.models.deletion.CASCADE, to='catalog.Illness')),
                ('patient', models.ForeignKey(help_text='病人姓名', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='藥物名稱', max_length=200)),
                ('duration', models.PositiveIntegerField(default=1, help_text='服用時間(周)')),
                ('freq', models.CharField(choices=[(' QD     ', '每日1次                    '), (' QD-INSL', '每日1次                    '), (' QDAC   ', '每日1次(用餐半小時前)      '), (' QDCC   ', '每日1次(餐後立即使用)      '), (' QDPC   ', '每日1次(用餐半小時後)      '), (' NOON   ', '每日中午1次                '), (' QPM    ', '每日下午1次                '), (' QN     ', '每晚1次                    '), (' HS     ', '每晚睡前1次                '), ('BID     ', '每日2次(早上、晚上)         '), ('BIDAN   ', '每日2次(早上、中午)         '), ('BIDAC   ', '每日早晚(用餐半小時前)      '), ('BIDACAN ', '早上及中午，用餐半小時前    '), ('BIDCC   ', '每日早晚(餐後立即使用)      '), ('BIDCCAN ', '早上及中午，餐後立即使用    '), ('BIDPC   ', '每日早晚(用餐半小時後)      '), ('BIDPCAN ', '早上及中午，用餐半小時後    '), ('QD&HS   ', '每日2次(早上、睡前)         '), ('BID&HS  ', '每日3次(早、晚、睡前)       '), ('TID     ', '每日3次                     '), ('TIDAC   ', '每日3餐半小時前             '), ('TIDCC   ', '每日3餐後立即使用           '), ('TIDPC   ', '每日3餐半小時後             '), ('QID     ', '每日4次(早午晚及睡前)       '), ('TID&HS  ', '每日4次(早午晚及睡前)       '), ('TIDAC&HS', '每日3餐半小時前及睡前   '), ('TIDCC&HS', '每日3餐後立即使用及睡前 '), ('TIDPC&HS', '每日3餐半小時後及睡前   '), ('PID     ', '每日5次，每次間隔4小時      '), ('QOD     ', '每隔1日1次                  '), ('QON     ', '每隔1晚1次                  '), ('Q3D     ', '每3日1次                    '), ('QW      ', '每週1次                     '), ('BIW     ', '每週2次                     '), ('TIW     ', '每週3次                     '), ('QM      ', '每月1次                     '), ('Q2H     ', '每2小時1次                  '), ('Q4H     ', '每4小時1次                  '), ('Q6H     ', '每6小時1次                  '), ('Q6HV    ', '每6小時1次                  '), ('Q8H     ', '每8小時1次                  '), ('Q8HV    ', '每8小時1次                  '), ('Q12H    ', '每12小時1次                 '), ('Q12HV   ', '每12小時1次                 '), ('QDPRN   ', '需要時每日1次               '), ('QNPRN   ', '需要時每晚1次               '), ('BIDPRN  ', '需要時每日2次(早晚)         '), ('TIDPRN  ', '需要時每日3次(早午晚)       '), ('QIDPRN  ', '需要時每日4次               '), ('Q5MPRN  ', '需要時每5分鐘1次            '), ('Q4HPRN  ', '需要時每4小時1次            '), ('Q6HPRN  ', '需要時每6小時1次            '), ('Q8HPRN  ', '需要時每8小時1次            '), ('Q12HPRN ', '需要時每12小時1次           '), ('Q3DPRN  ', '需要時每3日1次              '), ('ONCE    ', '1次                         '), ('STAT    ', '立刻使用                    '), ('2SQ6    ', '立刻2粒後，每6小時1次       '), ('ASOR    ', '遵照醫師指示                ')], help_text='請選擇藥物使用頻率', max_length=200)),
                ('treatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Treatment_record')),
            ],
        ),
    ]
