# Generated by Django 2.2.2 on 2019-07-17 15:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_patient_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='illness',
            name='selection',
            field=models.CharField(choices=[('severe', '重大疾病'), ('minor', '一般疾病')], default='minor', help_text='請選疾病是否為重症', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='past_illness',
            field=models.ManyToManyField(help_text='請選病人過去病史', related_name='past_illness', to='catalog.Illness'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='illness',
            field=models.ManyToManyField(help_text='請選病人患有什麼疾病', related_name='illness', to='catalog.Illness'),
        ),
        migrations.CreateModel(
            name='Severe_illness_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='發病日期')),
                ('illness', models.OneToOneField(help_text='重症名稱', on_delete=django.db.models.deletion.CASCADE, to='catalog.Illness')),
                ('patient', models.ForeignKey(help_text='病人姓名', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Patient')),
            ],
        ),
    ]
