# Generated by Django 2.2.2 on 2019-07-24 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190724_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment_record',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Patient'),
        ),
    ]
