# Generated by Django 2.2.2 on 2019-07-25 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190724_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['name'], 'permissions': (('doctor', 'Update or delete'),)},
        ),
        migrations.AddField(
            model_name='treatment_record',
            name='illness',
            field=models.ManyToManyField(blank=True, help_text='請選病人患有什麼疾病', to='catalog.Illness'),
        ),
        migrations.AlterField(
            model_name='severe_illness_record',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='病發日期'),
        ),
    ]
