# Generated by Django 2.2.2 on 2019-07-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190718_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='illness',
            options={'permissions': [('doctor', 'Update or delete')]},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'permissions': [('doctor', 'Update or delete')]},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'permissions': [('doctor', 'Update or delete')]},
        ),
        migrations.AlterModelOptions(
            name='severe_illness_record',
            options={'permissions': [('doctor', 'Update or delete')]},
        ),
        migrations.AlterModelOptions(
            name='treatment_record',
            options={'ordering': ['date'], 'permissions': [('doctor', 'Update or delete')]},
        ),
    ]
