# Generated by Django 2.2.2 on 2019-07-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190725_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='illness',
            field=models.ManyToManyField(blank=True, help_text='請選病人患有什麼疾病', related_name='illness', to='catalog.Illness'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='past_illness',
            field=models.ManyToManyField(blank=True, help_text='請選病人過去病史', related_name='past_illness', to='catalog.Illness'),
        ),
    ]
