# Generated by Django 2.2.2 on 2019-07-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190725_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='檢查日期')),
                ('Glu_Ac', models.PositiveIntegerField(help_text='mg/dl')),
                ('AST', models.PositiveIntegerField(help_text='IU/L')),
                ('ALT', models.PositiveIntegerField(help_text='IU/L')),
                ('CHO', models.PositiveIntegerField(help_text='mg/dl')),
                ('TG', models.PositiveIntegerField(help_text='mg/dl')),
                ('HDL', models.PositiveIntegerField(help_text='mg/dl')),
                ('BUN', models.PositiveIntegerField(help_text='mg/dl')),
                ('Cre', models.PositiveIntegerField(help_text='mg/dl')),
                ('UA', models.PositiveIntegerField(help_text='mg/dl')),
                ('CA', models.PositiveIntegerField(help_text='mg/dl')),
                ('LDH', models.PositiveIntegerField(help_text='mmol/L')),
                ('CK', models.PositiveIntegerField(help_text='mmol/L')),
                ('AMY', models.PositiveIntegerField(help_text='mmol/L')),
                ('Na', models.PositiveIntegerField(help_text='mmol/L')),
                ('K', models.PositiveIntegerField(help_text='mmol/L')),
                ('patient', models.ForeignKey(help_text='病人姓名', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Patient')),
            ],
        ),
    ]
