# Generated by Django 2.2.2 on 2019-07-27 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_inspection_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severe_illness_record',
            name='illness',
            field=models.ForeignKey(help_text='重症名稱', on_delete=django.db.models.deletion.CASCADE, to='catalog.Illness'),
        ),
    ]
