# Generated by Django 2.2.2 on 2019-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190728_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='illness',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergy',
            field=models.ManyToManyField(blank=True, help_text='過敏史', related_name='allergy', to='catalog.Medication'),
        ),
    ]
