# Generated by Django 2.2.2 on 2019-07-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190729_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment_record',
            name='treatment_detail',
            field=models.TextField(blank=True, default='S:\nO:\nP:', help_text='診斷紀錄', max_length=400),
        ),
    ]
