# Generated by Django 2.2.2 on 2019-07-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20190730_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatment_record',
            options={'ordering': ['-date'], 'permissions': (('doctor', 'Update or delete'),)},
        ),
    ]
