# Generated by Django 2.2.2 on 2019-07-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20190730_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection_report',
            options={'ordering': ['date']},
        ),
    ]
